# Generated by Django 5.1.1 on 2024-10-07 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioSite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='image',
        ),
    ]
